#!/usr/bin/php
<?php
    
require "src/helpers/helpers.php";
require 'vendor/autoload.php';

use Application\Messages\ShellMessager;

$input = $argv[1];

$messager = new ShellMessager;

$command = match($input)
{
    'migrate' => 'cd bin;php migrate',
    'migration' => "cd bin/;php migration {$argv[2]}",
    'server'=>'php -S localhost:8000 -t public/ ',
    'test'=>'php bin/test',
    'rollback'=> 'cd bin/;php rollback',
    'seeder' => "cd bin/;php seeder {$argv[2]}",
    'seed'  => 'cd bin/;php seed',
    'up' => 'cd bin/;php seed; php migrate',
    'both' => "cd bin/;php seeder {$argv[2]};php migration {$argv[2]}",
    'generate' => 'cd bin/;php generate',
    default => throw new Exception("Erro command  ( {$input} ) is not expected ")
};

echo shell_exec($command);