#!/usr/bin/php
<?php
    
require "src/helpers/helpers.php";

$input = $argv[1];

switch($input)
{
    case 'migrate':
        $command = 'cd bin;php migrate';
    break;
    case 'migration':
        $command = "cd bin/;php migration {$argv[2]}";
    break;
    case 'server':
        $command = 'cd bin/;php server ';
    break;
    case 'test':
        $command = 'php bin/test';
    break;
    case 'rollback':
        $command = 'cd bin/;php rollback';
    break;
    case 'seeder':
        $command = "cd bin/;php seeder {$argv[2]}";
    break;
    case 'seed':
        $command = 'cd bin/;php seed';
    break;
    case 'up':
        $command = 'cd bin/;php seed; php migrate';
    break;
    case 'both':
        $command = "cd bin/;php seeder {$argv[2]};php migration {$argv[2]}";
    break;
    default:
        throw new Exception('error code '.$argv[1].' is not expected');
    break;
}


echo shell_exec($command);